server:
  port: 9808

proxy:
  env: dev
  connectRetries: 5
  connectPause: 10
  timeout: 10000
  httpPort: 9111
  httpsPort: 9112
  listenPause: 50

#mongodb:
#  uri: mongodb://localhost/indoor_test

datasource:
  indoor:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
    maxActive: 50
    filters: stat,slf4j
    connectionProperties: druid.stat.slowSqlMillis=1000;druid.stat.mergeSql=true

httpclient:
  connectTimeout: 3000
  readTimeout: 10000
  maxConnection: 200
  maxConnectionPerHost: 20
  retry: 3

jsondoc:
  version: 1.0
  base-path: http://localhost:9100/
  packages:
    - com.wing